site_name: onshape-api
repo_url: https://github.com/imsenthur/onshape-api
site_url: https://imsenthur.github.io/onshape-api
site_description: A python library to facilitate interaction with Onshape's REST API
site_author: Senthur Ayyappan
edit_uri: edit/main/docs/
repo_name: imsenthur/onshape-api
copyright: Maintained by <a href="https://imsenthur.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/imsenthur/onshape-api
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/onshape-api

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
